// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/2pgcn/gameim/conf"
	"github.com/2pgcn/gameim/internal/logic/data"
	"github.com/2pgcn/gameim/internal/logic/server"
	"github.com/2pgcn/gameim/internal/logic/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
	_ "net/http/pprof"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	authService := service.NewAuthService(logger, dataData)
	grpcServer := server.NewGRPCServer(confServer, authService, logger)
	otherServer := server.NewOtherServer(confServer)
	app := newApp(logger, grpcServer, otherServer)
	return app, func() {
		cleanup()
	}, nil
}
